version: 2
jobs:
  test_5_1:
    docker: 
      - image: circleci/ruby:2.5.0-node
    working_directory: ~/where_chain
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - where_chain-bundle-{{ checksum "Gemfile.lock" }}
            - where_chain-bundle-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run: 
          name: 'Setup appraisals'
          command: bundle exec appraisal install

      - save_cache:
          key: where_chain-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: 
          name: 'Tests'
          command: bundle exec appraisal 5.1 rspec

      - store_test_results:
          path: test-results
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_5_1
